version: "3.2"
networks:
  internal:
    driver: bridge
services:
  web:
    build:
      context: .
    depends_on: [db]
    environment:
      APP_DB_USERNAME: ${DOCKER_APP_DB_USERNAME}
      APP_DB_PASSWORD: ${DOCKER_APP_DB_PASSWORD}
    ports: ["3000:3000"]
    networks: [internal]
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      APP_DB_USERNAME: ${DOCKER_APP_DB_USERNAME}
      APP_DB_PASSWORD: ${DOCKER_APP_DB_PASSWORD}
    expose: ["5432"]
    networks: [internal]
  cache: # needed to warm up cache_from; see https://github.com/docker/docker-py/issues/998
    image: "marnen/contraq:latest"
